# Generated by Django 3.0 on 2023-06-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
